# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate]
# Permalinks
permalink:        pretty

# Setup
title:            DarkFlow
tagline:          'Private Site'
description:      '博主Web前端死宅一枚，兼Blues吉他迷，欢迎交流'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
