# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems:             [jekyll-paginate]
# Permalinks
permalink:        pretty

# Setup
title:            Blue String
tagline:          'Private Site'
description:      '博主Web前端死宅一枚，兼Blues吉他迷，欢迎交流'
url:              http://darkflow.cc
baseurl:          /

author:
  name:           'ZeroDark1991'
  url:            https://github.com/ZeroDark1991

paginate:         5

# Custom vars
#version:          2.1.0

github:           https://github.com/ZeroDark1991
#  repo:           https://github.com/ZeroDark1991